### ISSUE TITLE
about result

### ISSUE THREAD

**Issue by soyekwon** [instantX-research/InstantStyle#52]
I run the code in the file info_style_controlnet.py in this github repo.
The results of the execution are as follows.

![다운로드 (99)](https://github.com/user-attachments/assets/8460f30a-84b1-4ea8-b91c-c496dcfecf80)

However, if you look at the picture of the result above, you can see something different compared to the picture of the paper result below.
![스크린샷 2024-09-09 오후 9 08 46](https://github.com/user-attachments/assets/e85a61fc-37d9-4458-b4b5-8bc5483041a1)

If I run the code directly in inf_style_controlnet.py, I get a very small dot-like artifact.
Why is that?

**Comment by soyekwon** [comment]
fix it.

**Comment by LWQGM** [comment]
May I ask how to fix it? Same problem here~
